### ISSUE TITLE
SYSTEMPROMPT variable not works

### ISSUE THREAD

**Issue by ratu-sh** [yym68686/ChatGPT-Telegram-Bot#61]
SYSTEMPROMPT variable not works.

do not know if it system wide or only in my certain case.

my set up is local run with python

also using custom API - gpt4free

when set SYSTEMPROMPT in export or .env or even in config.py - it is not work. chatbot ignores systemprompt.

can you also give example how string with SYSTEMPROMPT=*** should look like.
is it "quoted text string" or "file path"? how to escape special symbols in that prompt if any?

Thanks!

**Comment by yym68686** [comment]
Hello, the bug has been fixed. Please set CHAT_MODE to global, and the SYSTEMPROMPT setting will take effect. 

The setting of the system prompt is only effective when `CHAT_MODE` is `global`. When `CHAT_MODE` is `multiusers`, the system prompt environment variable will not modify any user's system prompt regardless of its value, because users do not want their set system prompt to be changed to the global system prompt.

**Comment by yym68686** [comment]
My local run has no issues. I believe it's because gpt4free does not support system prompts, so please try using the official OpenAI API instead. If there are still problems, please report them here.
